### ISSUE TITLE
Always Login at mobile device shows fail

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#4]
Sir,
When I am going to login from my mobile device same as my password and user name Always Login at mobile device shows fail

**Comment by rail5** [comment]
This might be a result of a difference in capitalization -- formerly, the CSS used in SimpleFS displayed all text in capital letters, so it would be possible to write (for example) "abc" and "ABC" and they would both look the same. Many phones automatically capitalize the first letter typed, and this wouldn't be noticed. This has been fixed in the latest version (2.0)

Let me know if that solves your problem

**Comment by techandtips86** [comment]
Thank you sir
