### ISSUE TITLE
Suggestion for Auto Delete Setting.

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#6]
Sir,
Good Morning, I just saw you update. this file and released new version. I uploaded it. But I have suggestion for it. If you look after this matter, it will more useful.
1.  Auto Delete setting should be on First Setup Page. (because of only who can edit auto delete setting , can create user id and password. you set this setting on upload page, in this page all user can edit it. (it is not necessary). At the first time when create user id and password, only this time can use or change auto delete setting.
2. When upload any file automatically shows a sharable link on this page. user can copy and send or share it. but this link in available when click download option.
3. Should be update with mail function.
4. Create a zip file. (As example i upload 5 files then when someone download it automatically create a zip files of 5 files and download as a zip file or make link as a shareable.

**Comment by rail5** [comment]
These are some good ideas

**1**: It's not a bad idea to add the "auto-delete" option to the setup page,
but I should point out that the auto-delete setting works *per-user*. Meaning,
if one user sets her auto-delete time to 10 days, that doesn't change the
setting of the other user, who could have it disabled for themselves, or set to
a different length.

I might add a separate "force auto-delete maximum for all users" setting
available only to the Administrator user. That doesn't sound too bad

**2**: That's an easy change & a good idea; I'll add it

**3**: I don't think adding a mail() function is appropriate. If SimpleFS used
PHP's built-in mail() function, most of those emails would end up in the
recipient's Spam folder. Otherwise, we would have to include something like
PHPMailer ( https://github.com/PHPMailer/PHPMailer ) & ask the user to enter
details for an account and an SMTP server. This would bloat SimpleFS; the goal
of SimpleFS is to be somewhat minimal, simple, and portable.

Besides, if the the 2nd change is made (showing the Download link immediately
after uploading a file), it's easy enough for users to just copy and paste that
link into an email themselves

**4**: Auto-creating zip files on "multi-file uploads" is a pretty good idea as
well. I could see that being very convenient & useful.


I think I'll go ahead and make those changes & release it as version 2.1

Thanks very much for providing input -- suggestions might not be *code*, but
they *are* valuable contributions to free & open-source software

**Comment by techandtips86** [comment]
Thank you sir. when you release update pls let me know and please mention what is you updated feature. Actually I am a Printing Engineer, all suggestion i am giving you as per my work experience in our field (Printing and Packaging Industries).

**Comment by techandtips86** [comment]
![Screen Shot 2023-04-26 at 12 17 28 PM](https://user-images.githubusercontent.com/127884368/234492373-6661cc62-8fcb-4235-878d-d379410a0a3d.png)
![Screen Shot 2023-04-26 at 12 18 10 PM](https://user-images.githubusercontent.com/127884368/234492383-47b39240-63a1-4f7e-aa71-731bc5261468.png)

**Comment by rail5** [comment]
Your suggestions #2 and #4 have now been added to SimpleFS version 2.1. I plan to re-work **setup.php** soon

SimpleFS now requires the php-zip module as well, to be able to create ZIP files. Version 2.1's **setup.php** will tell you whether the ZIP module is correctly installed
